export const economyConfig = {
  gamesPerSeries: 3,
  baseSponsorRevenueMonthly: 12000,
  baseTicketPrice: 12,
  averagePayrollPerPlayerMonthly: 2200,
  averageStaffCostsMonthly: 4200,
  averageFacilityUpkeepMonthly: 2600,
  averageScoutingBudgetMonthly: 1500,
  averageMarketingBudgetMonthly: 1200,
  baseMerchandiseStrength: 35,
  debtServiceRateWeekly: 0.0025,
  travelCostPerRoadGame: 350,
  stadiumExpansionSeatsPerUpgrade: 250,
  stadiumExpansionCostPerSeat: 160,
  stadiumExpansionUpkeepPerSeatMonthly: 1,
  stadiumExpansionCostGrowthPerLevel: 0.15,
};
